app:
    resource: "@AppBundle/Controller/"
    type:     annotation
homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage
userlist:
    path: /users
    defaults: { _controller : AppBundle:User:list }
user:
    path: /user/{userId}
    defaults: {_controller: AppBundle:User:user}
newuser:
    path: /newuser
    defaults: {_controller: AppBundle:User:newUser}